### ISSUE TITLE
Reorder Bug: Reordering of steps and content is not always saved 

### ISSUE THREAD

**Issue by Thiemann96** [reedu-reengineering-education/mapstories-2.0#207]
for example when you reorder a step and then delete one random step in the story, the reordering will not be applied and the order from before will be taken

**Comment by Mapstories** [comment]
Order of the media does not work at all. New order is not saved.

**Comment by Thiemann96** [comment]
As far as I can tell this was fixed by 4de9961 

I was not able to recreate the error, reopen this if it still does

**Comment by Mapstories** [comment]
This bug is still not fixed. The order of media set in StoryLab is thus not displayed in the preview view.

I cannot reopen the issue, can you do that?

**Comment by Thiemann96** [comment]
This issue is refereing to the ordering of **steps** which is working as intended as far as I can tell, will open a new issue which will be about the ordering of **media**

**Comment by Mapstories** [comment]
I opened the new issue, which is about the ordering of media.
